/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insert;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mohamed
 */
public class search extends javax.swing.JFrame implements ActionListener{
    private ImageIcon insertbackground = new ImageIcon(getClass().getResource("table.jpg"));
    private JLabel labelback = new JLabel();
    private String name ; 
    private String address ; 
    private String phone;
    private String sqlStatement ;
    /**
     * Creates new form search
     */
    //////////////////////////////////////////
    String age1 ;
    String age2 ; 
    //////////////////////////////////////////
    private String text_atfirst;
    public search() {
        initComponents();
        labelback.setIcon(insertbackground);
        labelback.setSize(this.getWidth(),this.getHeight());
        jPanel6.add(this.labelback);
        this.setVisible(true);
        this.setResizable(false);
        /////////////////////////////////////
         text_atfirst = set_age.getText();
         ////////////////////////////////////
         Cancel.addActionListener(this);
         Search_address.addActionListener(this);
         Search_age.addActionListener(this);
         Search_phone.addActionListener(this);
         Search_name.addActionListener(this);

         ////////////////////////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        Search_age = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        set_age = new javax.swing.JTextField();
        Set_address = new javax.swing.JTextField();
        Search_address = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Search_phone = new javax.swing.JButton();
        set_phone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        set_name = new javax.swing.JTextField();
        Search_name = new javax.swing.JButton();
        set_age1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        Search_age.setBackground(new java.awt.Color(24, 0, 84));
        Search_age.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        Search_age.setForeground(new java.awt.Color(255, 255, 255));
        Search_age.setText("Search");
        Search_age.setBorder(null);
        Search_age.setFocusPainted(false);

        Cancel.setBackground(new java.awt.Color(24, 0, 84));
        Cancel.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("Cancel");
        Cancel.setBorder(null);
        Cancel.setFocusPainted(false);

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Age Between");

        set_age.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        set_age.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        set_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_ageActionPerformed(evt);
            }
        });
        set_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                set_ageKeyTyped(evt);
            }
        });

        Set_address.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Set_address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        Set_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Set_addressActionPerformed(evt);
            }
        });

        Search_address.setBackground(new java.awt.Color(24, 0, 84));
        Search_address.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        Search_address.setForeground(new java.awt.Color(255, 255, 255));
        Search_address.setText("Search");
        Search_address.setBorder(null);
        Search_address.setFocusPainted(false);

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Enter the address");

        jLabel9.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Enter the Phone");

        Search_phone.setBackground(new java.awt.Color(24, 0, 84));
        Search_phone.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        Search_phone.setForeground(new java.awt.Color(255, 255, 255));
        Search_phone.setText("Search");
        Search_phone.setBorder(null);
        Search_phone.setFocusPainted(false);

        set_phone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        set_phone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        set_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_phoneActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Enter the Name ");

        set_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        set_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        set_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_nameActionPerformed(evt);
            }
        });

        Search_name.setBackground(new java.awt.Color(24, 0, 84));
        Search_name.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        Search_name.setForeground(new java.awt.Color(255, 255, 255));
        Search_name.setText("Search");
        Search_name.setBorder(null);
        Search_name.setFocusPainted(false);

        set_age1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        set_age1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        set_age1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_age1ActionPerformed(evt);
            }
        });
        set_age1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                set_age1KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel1.setText("and");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(set_name, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(set_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(set_age, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(set_age1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Set_address, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(110, 110, 110)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search_age, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(Search_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Search_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Search_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set_name, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_name, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search_address, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Set_address, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set_age1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Search_age, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(set_age, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void set_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set_ageActionPerformed

    private void Set_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Set_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Set_addressActionPerformed

    private void set_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set_phoneActionPerformed

    private void set_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set_nameActionPerformed

    private void set_age1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_age1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set_age1ActionPerformed

    private void set_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_set_ageKeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar(); 
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE)))
        { evt.consume(); }
    }//GEN-LAST:event_set_ageKeyTyped

    private void set_age1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_set_age1KeyTyped
        // TODO add your handling code here:
        char vChar = evt.getKeyChar(); 
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE)))
        { evt.consume(); }
    }//GEN-LAST:event_set_age1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Search_address;
    private javax.swing.JButton Search_age;
    private javax.swing.JButton Search_name;
    private javax.swing.JButton Search_phone;
    private javax.swing.JTextField Set_address;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField set_age;
    private javax.swing.JTextField set_age1;
    private javax.swing.JTextField set_name;
    private javax.swing.JTextField set_phone;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) { 
        if(e.getSource()==this.Search_name &&
                ( set_name.getText().equals(" ")
                ||(this.set_name.getText()).equals(text_atfirst)))
                {
                    JOptionPane.showMessageDialog(this,"please enter the name");
                }
        else if(e.getSource()==this.Search_phone &&
                ( set_phone.getText().equals(" ")
                ||(this.set_phone.getText()).equals(text_atfirst)))
            {
                    JOptionPane.showMessageDialog(this,"please enter the phone");
            }
        else if(e.getSource()==this.Search_address &&
                ( Set_address.getText().equals(" ")
                ||(this.Set_address.getText()).equals(text_atfirst)))
            {
                    JOptionPane.showMessageDialog(this,"please enter the address");
            }
        
        else if(e.getSource()==this.Search_age &&
                ( set_age.getText().equals(" ")||set_age1.getText().equals(" ")
                ||(this.set_age.getText()).equals(text_atfirst)||
                ((this.set_age1.getText()).equals(text_atfirst))))
            {
                    JOptionPane.showMessageDialog(this,"please enter the age");
            }
        
        else if(e.getSource()==this.Search_name)
        {
            
                name = this.set_name.getText();
                name = name.toLowerCase();
                sqlStatement = "select  name ,age , phone, patient_id from patient.patient " +
                        " where name like " +
                        "'%"+name+"%'";
            
            try {
                ///////////////////////////////////////////////////
                mainclass.connect_and_excute.select_function_with_name_address_phone(sqlStatement);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
            }
                this.dispose();
                // System.out.print("done");
            
        }
        else if(e.getSource()==this.Search_address)
        {
            
                address = this.Set_address.getText();
                address = address.toLowerCase();
                sqlStatement = "select  name ,age , phone, patient_id from patient.patient " +
                        " where address like " +
                        "'%"+address+"%'";
            
            try {
                ///////////////////////////////////////////////////
                mainclass.connect_and_excute.select_function_with_name_address_phone(sqlStatement);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
            }
                this.dispose();
                // System.out.print("done");
            
        }
        else if(e.getSource()==this.Search_phone)
        {
            
                phone = this.set_phone.getText();
                phone = phone.toLowerCase();
                sqlStatement = "select  name ,age , phone, patient_id from patient.patient " +
                        " where phone like " +
                        "'%"+phone+"%'";
            
            try {
                ///////////////////////////////////////////////////
                mainclass.connect_and_excute.select_function_with_name_address_phone(sqlStatement);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
            }
                this.dispose();
                // System.out.print("done");
            
        }
         else if(e.getSource()==this.Search_age)
        {
                
                 age1 = this.set_age.getText();
                 age2 = this.set_age1.getText();
                
                sqlStatement = "select  name ,age , phone, patient_id from patient.patient " +
                        " where age between " +
                        age1+" and "+age2;
            
            try {
                ///////////////////////////////////////////////////
                mainclass.connect_and_excute.select_function_with_name_address_phone(sqlStatement);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
            }
                this.dispose();
                // System.out.print("done");
            
        }
        else if (e.getSource()==this.Cancel)
        { 
            this.dispose();
        }
    }
}


